// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAu0DXRu-bwLh3b1DbRIs9FZgVFvuIMbgo',
//     appId: '1:293564839031:web:cc3311aa87878435bbc272',
//     messagingSenderId: '293564839031',
//     projectId: 'movieapp-b5385',
//     authDomain: 'movieapp-b5385.firebaseapp.com',
//     storageBucket: 'movieapp-b5385.appspot.com',
//     measurementId: 'G-RTE67NN8RC',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAF1-BbC_kp6KQ-lUzHldAbtVuFqSlDFoQ',
//     appId: '1:293564839031:android:5eefa470c1ecfd3cbbc272',
//     messagingSenderId: '293564839031',
//     projectId: 'movieapp-b5385',
//     storageBucket: 'movieapp-b5385.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAyh0RVnTnhY0K3CjerTgc-QBLn27i5pdY',
//     appId: '1:293564839031:ios:cb38596bcd842959bbc272',
//     messagingSenderId: '293564839031',
//     projectId: 'movieapp-b5385',
//     storageBucket: 'movieapp-b5385.appspot.com',
//     iosBundleId: 'com.example.movieapp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAyh0RVnTnhY0K3CjerTgc-QBLn27i5pdY',
//     appId: '1:293564839031:ios:cb38596bcd842959bbc272',
//     messagingSenderId: '293564839031',
//     projectId: 'movieapp-b5385',
//     storageBucket: 'movieapp-b5385.appspot.com',
//     iosBundleId: 'com.example.movieapp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAu0DXRu-bwLh3b1DbRIs9FZgVFvuIMbgo',
//     appId: '1:293564839031:web:c5f4d7a0b3494c91bbc272',
//     messagingSenderId: '293564839031',
//     projectId: 'movieapp-b5385',
//     authDomain: 'movieapp-b5385.firebaseapp.com',
//     storageBucket: 'movieapp-b5385.appspot.com',
//     measurementId: 'G-D6QS0VC906',
//   );
// }
